### ISSUE TITLE
Problems with config.ini and spotify_redirect_uri

### ISSUE THREAD

**Issue by arkdelkaos** [overthinkingme/SpotToPhones#5]
I had config the spotify dev panel, filled the config.ini with the id and secret, and the url I had selected for the callback is: http://localhost:8888/callback
But when my browser open the url from the terminal, I always get a error page:

```
Error
Oops! Something went wrong, please try again or check out our
```

I tried everything I could think off, but I can't get the login webpage to get the url I need to continue :(

**Comment by josevh** [comment]
It's possible that the config is not being read or not configured.
Is the config in the same directory?

I get the same error when I leave the config blank, the url:

```
https://accounts.spotify.com/authorize?scope=playlist-modify-private+playlist-read-private&redirect_uri=%7Bspotify+redirect+uri%7D&response_type=code&client_id=%7Bspotify+app+client+id%7D
```

which decodes to:

```
https://accounts.spotify.com/authorize?scope=playlist-modify-private playlist-read-private&redirect_uri={spotify redirect uri}&response_type=code&client_id={spotify app client id}
```

This sends me to the error page you described.

Otherwise I cannot replicate the issue.

**Comment by reveiler** [comment]
Im stuck on this same error, with various results.

when i python spottophones.py i get the output:

Please navigate here: https://accounts.spotify.com/authorize?scope=playlist-modify-private+playlist-read-private&redirect_uri=%7Blocalhost%3A8888%2Ffallback%7D&response_type=code&client_id=%7B11111111111111111111111111111111%7D
(1's changed to proper id)

This link gives the "oops" page straight away.

Ive removing the symbol translations from the url, (%7D etc) and then end up on the logon screen, log in, then it asks for permission to use the app. I accept and then end up on a "oops" screen. 

Doesn't the config.ini require the { } on each side? Should i remove them?

Ive also noticed that you wrote "Which decodes to: https://accounts.spotify.com/authorize?scope=playlist-modify-private playlist-read-private&redirect_uri={spotify redirect uri}&response_type=code&client_id={spotify app client id}

but no matter how many times i try I always end up with %20 (space) in the URL between "modify-private playlist-read" Does this make the URL get read wrong? Ive tried in Chrome and IE.

On the spotify dev site i read about changes to the way api works going into action now in may, does that affect the way SpotToPhones works today?

Is it me or is it Spotify's newest updates screwing things over?
See https://developer.spotify.com/news-stories/2016/03/29/api-improvements-update/

Thanks again for your time and effort.

**Comment by josevh** [comment]
@reveiler Thanks for the heads up on the api. I will try to update the implementation.

For the config, please don't use brackets, I will update the example file. Apologies for the confusion.

Also, the config must be filled out with your information
You need a spotify and echonest developer account to get the info for the config.
I made this so that anyone can put their dev account info.

Once you grant the app access, you need to paste the url the page you're redirected to into the terminal.

I will also try a fresh install to validate errors reported.

I will probably rewrite this to have GUI in php soon which should ease confusion but no ETA yet.

**Comment by reveiler** [comment]
Alright thanks. 
I tried again today, edited the config.ini without brackets and simplified the config as much as i could.

https://accounts.spotify.com/en/authorize?scope=playlist-modify-private&redirect_uri=localhost:8000&response_type=code&client_id=1111111111111111111

If im not already logged in to spotify, it asks me to log in, then asks for app permission. 
As soon as i click "Okay" in Chrome it does nothing, If i then retry loading the link, i end up with a page saying "INVALID_CLIENT: Invalid redirect URI"
On IE the first part is the same, but if i retry the link when logged in I end up on "HTTP 400 Bad Request Webpage cannot be found."

Thanks for quick reply, and appreciate doing the "for dummies" part :D

Edit: I got to the right page. Remembering to save changes on the Spotify Dev page helps.
Thanks again!

**Comment by josevh** [comment]
@reveiler I was looking over the changes coming and it looks like the ability to map Musicbrainz IDs to Spotify IDs was not migrated to the Spotify API. That said, this program will break as of May 31. The alternative is to map manually with GUI or attempt best-guess automatic matching. Not sure what I'll proceed with, if at all.
