### ISSUE TITLE
how-to documentation

### ISSUE THREAD

**Issue by reveiler** [overthinkingme/SpotToPhones#6]
Hello and thanks for something i believe is a great project and idea. If i only got it to work.

Are there any installation guides on this except the 1-3 requirements?
Ive managed installing all the requirements,edited the config file as far as I could but now im stuck. 

I have no idea on where to get the spotify client id, uri etc. 
I've tried googling it but end up on the general spotify developer page, where i dont feel at home at all.

Any chance you'll ever create a "for dummies" howto ?

Thanks in advance.

**Comment by reveiler** [comment]
Ive tried using the echonest information as client id and shared secret, but when i enter the web address that pops up when i run the script, i always end up on a page saying "INVALID_CLIENT: Invalid client" so i take it ive got the wrong client ID.

**Comment by reveiler** [comment]
Ive now managed to end up with "Failed to get client" which is progress. 
But something just struck me, am i required to have premium spotify to get this working?

**Comment by josevh** [comment]
@reveiler Sorry for the lack of documentation. I'll update it tonight. I am in the process of rewriting the whole thing. I suggest you don't sync repo as it is not in a working state as of a code push last night. Almost done.

You get a spotify client id, uri, secret from spotify from their developer site
https://developer.spotify.com/my-applications/

Spotify Premium is not required.

**Comment by josevh** [comment]
regarding Spotify client_id, client_secret, redirect_uri:
you must register an app on Spotify
https://developer.spotify.com/my-applications/#!/

It will provide you the required information needed.
Similarly you'll need developer credentials for Echonest

I provided a description of each field of the config.ini in the README.
I've also put examples in the config.ini.example file.

I will close this for now.
